services:
  punch-scheduler:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime

    image: ghcr.io/madfater/aoacloudepunchio:latest
    container_name: aoacloude-punch-scheduler
    restart: unless-stopped

    ipc: host
    shm_size: 2gb

    env_file:
      - .env
    environment:
      TZ: Asia/Taipei
      PYTHONUNBUFFERED: "1"
      LOG_LEVEL: INFO
      SCREENSHOT_ENABLED: "true"

    volumes:
      - ./logs:/app/logs:rw
      - ./screenshots:/app/screenshots:rw
      - ./.env:/app/.env:ro

    healthcheck:
      test: ["CMD", "python", "-c", "import sys; sys.path.insert(0, '/app/src'); from config import config_manager; config_manager.load_config(); print('Config loaded successfully')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

    deploy:
      resources:
        limits:
          memory: 2G
          cpus: "1.0"
        reservations:
          memory: 512M
          cpus: "0.25"

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
